name: biobuild2
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - expat=2.5.0
  - fontconfig=2.14.2
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.69.1
  - icu=73.2
  - libcxx=14.0.6
  - libexpat=2.5.0
  - libffi=3.4.4
  - libiconv=1.17
  - libpng=1.6.39
  - libxml2=2.11.5
  - libzlib=1.2.13
  - ncurses=6.4
  - openbabel=3.1.1
  - openssl=3.1.2
  - pcre=8.45
  - pip=23.2.1
  - pixman=0.40.0
  - python=3.11.4
  - python_abi=3.11
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - about-time==4.2.1
      - alive-progress==3.1.4
      - appnope==0.1.3
      - asttokens==2.2.1
      - attrs==23.1.0
      - backcall==0.2.0
      - biopython==1.81
      - cloudpickle==2.2.1
      - comm==0.1.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - debugpy==1.6.7.post1
      - decorator==5.1.1
      - executing==1.2.0
      - fonttools==4.42.1
      - grapheme==0.6.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - iniconfig==2.0.0
      - ipykernel==6.25.1
      - ipython==8.14.0
      - ipywidgets==8.0.0
      - jedi==0.19.0
      - joblib==1.3.2
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyterlab-widgets==3.0.8
      - kiwisolver==1.4.5
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - nest-asyncio==1.5.7
      - networkx==3.1
      - nglview==3.0.6
      - numpy==1.25.2
      - openmm==0.2
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - pdbecif==1.5
      - periodictable==1.6.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - platformdirs==3.10.0
      - plotly==5.16.1
      - pluggy==1.3.0
      - prompt-toolkit==3.0.39
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pubchempy==1.0.4
      - pure-eval==0.2.2
      - py3dmol==2.0.3
      - pygments==2.16.1
      - pyparsing==3.0.9
      - pytest==7.4.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyzmq==25.1.1
      - rdkit==2023.3.3
      - scikit-learn==1.3.0
      - scipy==1.11.2
      - seaborn==0.12.2
      - six==1.16.0
      - stack-data==0.6.2
      - swig==4.1.1
      - tabulate==0.9.0
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - tornado==6.3.3
      - traitlets==5.9.0
      - tzdata==2023.3
      - wcwidth==0.2.6
      - widgetsnbextension==4.0.8
